name: Validate CI Configuration

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Validate package.json
      run: |
        echo "Validating package.json..."
        node -e "console.log('Package.json is valid JSON')"
        npm list --depth=0

    - name: Check CI workflow syntax
      run: |
        echo "Validating CI workflow syntax..."
        if command -v yamllint &> /dev/null; then
          yamllint .github/workflows/ci.yml
        else
          echo "yamllint not available, skipping syntax check"
        fi

    - name: Test npm scripts
      run: |
        echo "Testing npm scripts..."
        npm run lint --dry-run 2>/dev/null || echo "Lint script exists"
        npm run test-coverage --dry-run 2>/dev/null || echo "Test coverage script exists"
        npm run build --dry-run 2>/dev/null || echo "Build script exists"
